"""
Built-in Hooks Module
=====================

Provides built-in hooks for common automation tasks:
- doc_update_hook: Generate/update documentation after coding
- run_tests_hook: Run tests after each step
- git_commit_hook: Auto-commit after phase completion
- lint_hook: Run linting on generated code
"""

import asyncio
import subprocess
import logging
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


async def doc_update_hook(context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Update documentation based on generated code.

    Context expected:
    - project_dir: Path to project
    - generated_files: Dict of filepath -> content
    - original_request: User's original request
    - llm_client: Optional LLM client for generating docs
    - phase: Optional current phase (PLANNING, ARCHITECTURE, DESIGN, CODING, COMPLETE)
    - phase_context: Optional full context from the phase (for enhanced doc generation)

    If phase_context is provided, uses DocumentationGenerator for comprehensive docs.
    Otherwise, falls back to basic README generation.

    Returns:
        Dict with action taken and results
    """
    project_dir = Path(context.get('project_dir', '.'))
    generated_files = context.get('generated_files', {})
    original_request = context.get('original_request', '')
    phase = context.get('phase', '')
    phase_context = context.get('phase_context', {})

    # If we have full phase context, use DocumentationGenerator
    if phase_context and phase:
        try:
            from .doc_generator import DocumentationGenerator

            generator = DocumentationGenerator(project_dir, phase_context)

            if phase.upper() == 'COMPLETE':
                # Generate all documentation
                results = generator.generate_all()
                success_count = sum(1 for v in results.values() if v)
                logger.info(f"DocumentationGenerator: {success_count}/{len(results)} files generated")

                return {
                    'action': 'generated',
                    'generator': 'DocumentationGenerator',
                    'phase': phase,
                    'results': results
                }
            else:
                # Generate phase-specific documentation
                success = generator.generate_phase_doc(phase, phase_context)
                return {
                    'action': 'generated' if success else 'failed',
                    'generator': 'DocumentationGenerator',
                    'phase': phase
                }

        except ImportError as e:
            logger.warning(f"DocumentationGenerator not available: {e}")
            # Fall through to basic generation
        except Exception as e:
            logger.error(f"DocumentationGenerator failed: {e}")
            # Fall through to basic generation

    # Fallback: Basic README generation
    readme_path = project_dir / "README.md"

    # Check if README exists
    if readme_path.exists():
        logger.debug("README.md already exists, skipping auto-generation")
        return {
            'action': 'skipped',
            'reason': 'README already exists',
            'file': str(readme_path)
        }

    # Generate basic README if we have files
    if not generated_files:
        return {
            'action': 'skipped',
            'reason': 'No generated files to document'
        }

    # Build basic README content
    file_list = '\n'.join(f"- `{f}`" for f in sorted(generated_files.keys()))

    readme_content = f"""# Generated Project

## Description

{original_request[:500] if original_request else 'Auto-generated project'}

## Files

{file_list}

## Generated

Generated by CLI Coding Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Usage

```bash
# Install dependencies
pip install -r requirements.txt

# Run the application
python main.py
```
"""

    try:
        readme_path.write_text(readme_content)
        logger.info(f"Generated README.md at {readme_path}")

        return {
            'action': 'created',
            'file': str(readme_path),
            'size': len(readme_content)
        }

    except Exception as e:
        logger.error(f"Failed to create README: {e}")
        return {
            'action': 'failed',
            'error': str(e)
        }


async def run_tests_hook(context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run tests after each step.

    Context expected:
    - project_dir: Path to project
    - language: Programming language (python, javascript, etc.)

    Returns:
        Dict with test results
    """
    project_dir = Path(context.get('project_dir', '.'))
    language = context.get('language', 'python').lower()

    # Determine test command based on language
    from agents.common.config_defaults import DEFAULT_TEST_COMMANDS
    test_commands = DEFAULT_TEST_COMMANDS

    command = test_commands.get(language)

    if not command:
        logger.debug(f"No test command for language: {language}")
        return {
            'success': True,
            'skipped': True,
            'reason': f'No test command for {language}'
        }

    # Check if test framework is available
    if language == 'python':
        # Check for pytest or tests directory
        has_pytest = (project_dir / 'pytest.ini').exists() or \
                     (project_dir / 'tests').exists() or \
                     (project_dir / 'test').exists()

        # Also check for test files
        test_files = list(project_dir.glob('**/test_*.py')) + \
                     list(project_dir.glob('**/*_test.py'))

        if not has_pytest and not test_files:
            return {
                'success': True,
                'skipped': True,
                'reason': 'No tests found'
            }

    try:
        # Run tests with timeout
        result = await asyncio.to_thread(
            subprocess.run,
            command,
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=60
        )

        success = result.returncode == 0

        return {
            'success': success,
            'returncode': result.returncode,
            'stdout': result.stdout[:2000] if result.stdout else '',
            'stderr': result.stderr[:500] if result.stderr else '',
            'command': ' '.join(command)
        }

    except subprocess.TimeoutExpired:
        return {
            'success': False,
            'error': 'Test execution timed out after 60s'
        }

    except FileNotFoundError as e:
        return {
            'success': True,
            'skipped': True,
            'reason': f'Test command not found: {e}'
        }

    except Exception as e:
        return {
            'success': False,
            'error': str(e)
        }


async def git_commit_hook(context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Create git commit after phase completion.

    Context expected:
    - project_dir: Path to project
    - phase: Current development phase
    - commit_message: Optional custom commit message

    Returns:
        Dict with commit results
    """
    project_dir = Path(context.get('project_dir', '.'))
    phase = context.get('phase', 'UNKNOWN')
    custom_message = context.get('commit_message')

    git_dir = project_dir / '.git'

    # Initialize git if not exists
    if not git_dir.exists():
        try:
            init_result = await asyncio.to_thread(
                subprocess.run,
                ['git', 'init'],
                cwd=str(project_dir),
                capture_output=True,
                text=True,
                timeout=30
            )
            logger.info("Initialized git repo in %s", project_dir)
        except Exception as e:
            logger.error("Failed to init git: %s", e)
            return {
                'success': False,
                'error': f'Failed to init git: {e}'
            }

    try:
        # Stage all changes
        stage_result = await asyncio.to_thread(
            subprocess.run,
            ['git', 'add', '-A'],
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=30
        )

        if stage_result.returncode != 0:
            return {
                'success': False,
                'error': f'Failed to stage files: {stage_result.stderr}'
            }

        # Check if there are changes to commit
        status_result = await asyncio.to_thread(
            subprocess.run,
            ['git', 'status', '--porcelain'],
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=30
        )

        if not status_result.stdout.strip():
            return {
                'success': True,
                'skipped': True,
                'reason': 'No changes to commit'
            }

        # Create commit message
        if custom_message:
            commit_message = custom_message
        else:
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            commit_message = f"[{phase}] Auto-commit by CLI Coding Agent\n\nGenerated: {timestamp}"

        # Commit
        commit_result = await asyncio.to_thread(
            subprocess.run,
            ['git', 'commit', '-m', commit_message],
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=30
        )

        if commit_result.returncode != 0:
            # Check if it's just "nothing to commit"
            if 'nothing to commit' in commit_result.stdout.lower():
                return {
                    'success': True,
                    'skipped': True,
                    'reason': 'Nothing to commit'
                }

            return {
                'success': False,
                'error': f'Failed to commit: {commit_result.stderr}'
            }

        # Get commit hash
        hash_result = await asyncio.to_thread(
            subprocess.run,
            ['git', 'rev-parse', '--short', 'HEAD'],
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=10
        )

        commit_hash = hash_result.stdout.strip() if hash_result.returncode == 0 else 'unknown'

        return {
            'success': True,
            'commit_hash': commit_hash,
            'message': commit_message,
            'phase': phase
        }

    except subprocess.TimeoutExpired:
        return {
            'success': False,
            'error': 'Git operation timed out'
        }

    except Exception as e:
        logger.error("Git hook failed: %s", e)
        return {
            'success': False,
            'error': str(e)
        }


async def run_linter(
    project_dir: Path,
    language: str,
    files: Optional[list] = None
) -> Dict[str, Any]:
    """
    Run linter for a specific language.

    Args:
        project_dir: Root directory of project
        language: Programming language
        files: Optional list of files to lint

    Returns:
        Dict with lint results
    """
    from agents.common.config_defaults import DEFAULT_LINT_COMMANDS

    language_lower = language.lower()
    command = DEFAULT_LINT_COMMANDS.get(language_lower)

    if not command:
        logger.debug("No lint command configured for language: %s", language)
        return {
            'success': True,
            'skipped': True,
            'reason': f'No lint command for {language}'
        }

    # Pre-flight checks for specific linters
    if language_lower == 'python':
        # Check if flake8 is installed
        try:
            check_result = subprocess.run(
                ['python', '-m', 'flake8', '--version'],
                capture_output=True,
                text=True,
                timeout=10
            )
            if check_result.returncode != 0 or 'No module named' in check_result.stderr:
                logger.warning("flake8 not installed, skipping Python linting")
                return {
                    'success': True,
                    'skipped': True,
                    'reason': 'flake8 not installed (pip install flake8)'
                }
        except Exception:
            return {
                'success': True,
                'skipped': True,
                'reason': 'Could not verify flake8 installation'
            }

    elif language_lower in ['javascript', 'typescript']:
        # Check if eslint config exists - if not, skip to avoid long npx download
        eslint_configs = ['.eslintrc', '.eslintrc.js', '.eslintrc.json', '.eslintrc.yml', 'eslint.config.js']
        has_eslint_config = any((project_dir / cfg).exists() for cfg in eslint_configs)

        # Also check package.json for eslint
        pkg_json = project_dir / 'package.json'
        has_eslint_in_pkg = False
        if pkg_json.exists():
            try:
                import json
                with open(pkg_json) as f:
                    pkg_data = json.load(f)
                    deps = {**pkg_data.get('dependencies', {}), **pkg_data.get('devDependencies', {})}
                    has_eslint_in_pkg = 'eslint' in deps
            except Exception:
                pass

        if not has_eslint_config and not has_eslint_in_pkg:
            logger.info("No ESLint config found, skipping JS/TS linting")
            return {
                'success': True,
                'skipped': True,
                'reason': 'No ESLint configuration found'
            }

    # Make a copy to avoid modifying the global default
    cmd_list = list(command)

    # Add specific files if provided
    if files:
        cmd_list.extend(files)
    elif language_lower == 'python':
        cmd_list.append('.')

    logger.info("Running linter for %s: %s", language, ' '.join(cmd_list))
    start_time = datetime.now()

    # Use shorter timeout for JS/TS to avoid npx download issues
    timeout = 30 if language_lower in ['javascript', 'typescript'] else 60

    try:
        result = await asyncio.to_thread(
            subprocess.run,
            cmd_list,
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=timeout
        )

        duration = (datetime.now() - start_time).total_seconds()

        # Check for module not found errors (common with Python linters)
        output = result.stdout + result.stderr
        if 'No module named' in output:
            logger.warning("Linter module not found: %s", output[:200])
            return {
                'success': True,
                'skipped': True,
                'reason': f'Linter module not installed'
            }

        # For linting, warnings are ok (returncode might be non-zero)
        issues = result.stdout if result.stdout else result.stderr
        has_issues = result.returncode != 0

        if has_issues:
            logger.warning("Linting found issues in %.1fs", duration)
        else:
            logger.info("Linting passed in %.1fs", duration)

        return {
            'success': True,  # Lint ran successfully even if there are issues
            'has_issues': has_issues,
            'issues': issues[:2000] if issues else '',
            'returncode': result.returncode,
            'duration': duration
        }

    except subprocess.TimeoutExpired:
        logger.warning("Linter timed out for %s after %ds", language, timeout)
        return {
            'success': True,
            'skipped': True,
            'reason': f'Linter timed out (>{timeout}s)'
        }

    except FileNotFoundError:
        logger.warning("Linter executable not found for %s", language)
        return {
            'success': True,
            'skipped': True,
            'reason': 'Linter not installed'
        }

    except Exception as e:
        logger.error("Linter execution failed: %s", e)
        return {
            'success': False,
            'error': str(e)
        }


async def lint_hook(context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run linting on generated code.

    Context expected:
    - project_dir: Path to project
    - language: Programming language
    - files: Optional list of specific files to lint

    Returns:
        Dict with lint results
    """
    project_dir = Path(context.get('project_dir', '.'))
    language = context.get('language', 'python').lower()
    files = context.get('files')

    return await run_linter(project_dir, language, files)


# Hook registration helper
def register_builtin_hooks(hook_manager, config: Optional[Dict[str, Any]] = None):
    """
    Register all built-in hooks with the hook manager.

    Args:
        hook_manager: HookManager instance
        config: Optional configuration dict to enable/disable specific hooks
    """
    from .hook_manager import HookDefinition, HookTrigger

    config = config or {}

    # Helper to safely get hook config
    def get_hook_config(hook_name: str, default_enabled: bool = True) -> Dict[str, Any]:
        hook_cfg = config.get(hook_name)
        if hook_cfg is None:
            return {'enabled': default_enabled}
        if isinstance(hook_cfg, bool):
            return {'enabled': hook_cfg}
        if isinstance(hook_cfg, dict):
            return hook_cfg
        return {'enabled': default_enabled}

    # doc_update hook
    doc_config = get_hook_config('doc_update', True)
    if doc_config.get('enabled', True):
        hook_manager.register(HookDefinition(
            name='doc_update',
            trigger=HookTrigger.PHASE_END,
            handler=doc_update_hook,
            phases=doc_config.get('phases', ['CODING', 'DEBUGGING']),
            priority=50,
            description='Generate/update project documentation'
        ))

    # run_tests hook
    tests_config = get_hook_config('run_tests', True)
    if tests_config.get('enabled', True):
        hook_manager.register(HookDefinition(
            name='run_tests',
            trigger=HookTrigger.STEP_END,
            handler=run_tests_hook,
            priority=100,
            description='Run tests after each step'
        ))

    # git_commit hook
    commit_config = get_hook_config('git_commit', True)
    if commit_config.get('enabled', True):
        hook_manager.register(HookDefinition(
            name='git_commit',
            trigger=HookTrigger.PHASE_END,
            handler=git_commit_hook,
            phases=commit_config.get('phases', ['CODING', 'DEBUGGING', 'TESTING']),
            priority=200,  # Run after other hooks
            description='Auto-commit changes after phase completion'
        ))

    # lint hook
    lint_config = get_hook_config('lint', False)
    if lint_config.get('enabled', False):  # Disabled by default
        hook_manager.register(HookDefinition(
            name='lint',
            trigger=HookTrigger.FILE_GENERATED,
            handler=lint_hook,
            priority=75,
            description='Run linting on generated code'
        ))

    logger.info("Built-in hooks registered")
