"""
Bug Test Generator
==================

Generates bug-specific tests that:
1. Reproduce the exact bug condition
2. FAIL before the fix (confirming bug exists)
3. PASS after the fix (confirming bug is fixed)

This is the key to autonomous debugging - if we can't reproduce it, we can't fix it.

Language-agnostic: Uses LanguageDetector to generate tests in the project's language.
"""

import asyncio
import logging
import subprocess
import tempfile
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Dict, Any

from ..services.language_detector import LanguageDetector, LanguageInfo

logger = logging.getLogger(__name__)


@dataclass
class TestResult:
    """Result of running a test."""
    passed: bool
    output: str
    error: Optional[str] = None
    duration_seconds: float = 0.0


class BugTestGenerator:
    """
    Generate tests that reproduce specific bugs.

    The generated test should:
    1. Set up the conditions that trigger the bug
    2. Execute the code path that fails
    3. Assert what SHOULD happen (will fail when bug exists)
    """

    # Template for generated bug tests
    TEST_TEMPLATE = '''"""
Bug-specific test generated by RAICA.

Bug Description: {bug_description}
Generated: {timestamp}
"""

import pytest
import sys
from pathlib import Path

# Add project to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

{imports}


class TestBug_{test_id}:
    """Test case for: {bug_description_short}"""

    def test_bug_reproduction(self):
        """
        This test reproduces the bug.
        - Should FAIL before fix (bug exists)
        - Should PASS after fix (bug resolved)
        """
        {test_body}
'''

    def __init__(self, llm_client: Any, project_dir: Path, language_detector: Optional[LanguageDetector] = None):
        self.llm_client = llm_client
        self.project_dir = project_dir
        self.language_detector = language_detector or LanguageDetector(project_dir)
        self._ui_framework_cache = None

    def _check_dependency(self, python_path: str, import_name: str) -> bool:
        """Check if a dependency can be imported in the given Python environment."""
        try:
            cmd = [python_path, "-c", f"import {import_name}"]
            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

    def _install_dependency(self, python_path: str, package_name: str) -> bool:
        """Install a dependency into the project venv."""
        try:
            logger.info(f"[Install] Installing {package_name} into project venv...")
            cmd = [python_path, "-m", "pip", "install", package_name, "-q"]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            if result.returncode == 0:
                logger.info(f"[Install] ✓ Successfully installed {package_name}")
                return True
            else:
                logger.warning(f"[Install] ✗ Failed to install {package_name}: {result.stderr}")
                return False
        except subprocess.TimeoutExpired:
            logger.warning(f"[Install] ✗ Timeout installing {package_name}")
            return False
        except Exception as e:
            logger.warning(f"[Install] ✗ Error installing {package_name}: {e}")
            return False

    def _ensure_test_dependencies(self, python_path: str) -> bool:
        """
        Ensure the project venv has all required test dependencies.
        Installs missing dependencies automatically.

        Returns:
            True if all dependencies are available (installed or already present)
        """
        # Required: pytest
        if not self._check_dependency(python_path, "pytest"):
            logger.info(f"[Dependencies] pytest not found, installing...")
            if not self._install_dependency(python_path, "pytest"):
                return False

        # Framework-specific dependencies
        framework = self._detect_ui_framework()
        logger.info(f"[Dependencies] Detected UI framework: {framework}")

        if framework in ('pyqt5', 'pyqt6', 'pyside2', 'pyside6'):
            if not self._check_dependency(python_path, "pytestqt"):
                logger.info(f"[Dependencies] pytest-qt not found for {framework} project, installing...")
                if not self._install_dependency(python_path, "pytest-qt"):
                    return False
            if not self._check_dependency(python_path, "pytest_mock"):
                logger.info(f"[Dependencies] pytest-mock not found, installing...")
                self._install_dependency(python_path, "pytest-mock")  # Optional, don't fail if missing

        logger.info(f"[Dependencies] ✓ All test dependencies satisfied")
        return True

    def _create_venv(self) -> Optional[Path]:
        """Create a new virtual environment for the project."""
        try:
            logger.info(f"[PythonPath] Creating new venv at {self.project_dir / '.venv'}...")
            subprocess.run([sys.executable, "-m", "venv", str(self.project_dir / ".venv")], check=True)
            
            venv_path = self.project_dir / ".venv"
            python_bin = venv_path / "bin" / "python"
            if not python_bin.exists():
                python_bin = venv_path / "Scripts" / "python.exe"
            
            if python_bin.exists():
                logger.info(f"[PythonPath] ✓ Created venv: {python_bin}")
                # Upgrade pip
                subprocess.run([str(python_bin), "-m", "pip", "install", "--upgrade", "pip"], 
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                return python_bin
            return None
        except Exception as e:
            logger.error(f"[PythonPath] Failed to create venv: {e}")
            return None

    def _get_project_python_path(self) -> str:
        """
        Get the path to the python executable for this project.
        Finds project venv and ensures test dependencies are installed.

        IMPORTANT: This method ONLY uses the project's venv. It will NOT
        fall back to RAICA's venv or system Python for running project tests.
        """
        venv_names = [".venv", "venv", "env"]

        logger.info(f"[PythonPath] Searching for venv in project_dir: {self.project_dir}")

        for name in venv_names:
            venv_path = self.project_dir / name
            if venv_path.exists() and venv_path.is_dir():
                # Check for bin/python (Linux/Mac) or Scripts/python.exe (Windows)
                python_bin = venv_path / "bin" / "python"
                if not python_bin.exists():
                    python_bin = venv_path / "Scripts" / "python.exe"  # Windows

                if python_bin.exists() and python_bin.is_file():
                    logger.info(f"[PythonPath] Found project venv: {python_bin}")
                    # Ensure test dependencies are installed (installs if missing)
                    if self._ensure_test_dependencies(str(python_bin)):
                        logger.info(f"[PythonPath] ✓ Using project venv with all dependencies: {python_bin}")
                        return str(python_bin)
                    else:
                        logger.error(f"[PythonPath] ✗ Failed to ensure dependencies in {venv_path}")
                        # Still use project venv - better to fail clearly than use wrong env
                        return str(python_bin)

        # No project venv found - attempt to create one
        logger.warning(f"[PythonPath] ✗ No project venv found in {self.project_dir}")
        logger.info(f"[PythonPath] Attempting to auto-create virtual environment...")
        
        created_python = self._create_venv()
        if created_python:
            # Install dependencies if requirements.txt exists
            req_file = self.project_dir / "requirements.txt"
            if req_file.exists():
                logger.info(f"[PythonPath] Installing requirements from {req_file}...")
                subprocess.run([str(created_python), "-m", "pip", "install", "-r", str(req_file)],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            
            # Ensure test dependencies
            if self._ensure_test_dependencies(str(created_python)):
                 return str(created_python)
        
        # Return system python as last resort, but log a clear warning
        system_python = Path("/usr/bin/python3")
        if system_python.exists():
            logger.warning(f"[PythonPath] ⚠ Using system python (may fail for project imports): {system_python}")
            return str(system_python)

        raise RuntimeError(f"No Python environment found and failed to create one at {self.project_dir}.")

    def _detect_ui_framework(self) -> Optional[str]:
        """
        Detect the UI framework used in the project.

        Returns:
            Framework name: 'pyqt5', 'pyqt6', 'pyside2', 'pyside6', 'tkinter',
                           'wxpython', 'kivy', 'react', 'vue', 'angular', 'electron', None
        """
        if self._ui_framework_cache is not None:
            logger.debug(f"[Framework] Using cached: {self._ui_framework_cache}")
            return self._ui_framework_cache

        logger.info(f"[Framework] Detecting UI framework in: {self.project_dir}")
        # Check requirements.txt for Python UI frameworks
        req_file = self.project_dir / "requirements.txt"
        logger.info(f"[Framework] Checking {req_file}, exists={req_file.exists()}")
        if req_file.exists():
            try:
                content = req_file.read_text().lower()
                if 'pyqt5' in content:
                    logger.info(f"[Framework] ✓ Found PyQt5 in requirements.txt")
                    self._ui_framework_cache = 'pyqt5'
                    return 'pyqt5'
                elif 'pyqt6' in content:
                    self._ui_framework_cache = 'pyqt6'
                    return 'pyqt6'
                elif 'pyside2' in content:
                    self._ui_framework_cache = 'pyside2'
                    return 'pyside2'
                elif 'pyside6' in content:
                    self._ui_framework_cache = 'pyside6'
                    return 'pyside6'
                elif 'wxpython' in content or 'wx' in content:
                    self._ui_framework_cache = 'wxpython'
                    return 'wxpython'
                elif 'kivy' in content:
                    self._ui_framework_cache = 'kivy'
                    return 'kivy'
            except Exception:
                pass

        # Check for tkinter usage in Python files
        try:
            for py_file in self.project_dir.rglob("*.py"):
                if py_file.is_file():
                    content = py_file.read_text()
                    if 'import tkinter' in content or 'from tkinter' in content:
                        self._ui_framework_cache = 'tkinter'
                        return 'tkinter'
                    if 'from PyQt5' in content or 'import PyQt5' in content:
                        self._ui_framework_cache = 'pyqt5'
                        return 'pyqt5'
                    if 'from PyQt6' in content or 'import PyQt6' in content:
                        self._ui_framework_cache = 'pyqt6'
                        return 'pyqt6'
                    if 'from PySide2' in content or 'import PySide2' in content:
                        self._ui_framework_cache = 'pyside2'
                        return 'pyside2'
                    if 'from PySide6' in content or 'import PySide6' in content:
                        self._ui_framework_cache = 'pyside6'
                        return 'pyside6'
        except Exception:
            pass

        # Check package.json for JS frameworks
        pkg_json = self.project_dir / "package.json"
        if pkg_json.exists():
            try:
                import json
                content = json.loads(pkg_json.read_text())
                deps = {**content.get('dependencies', {}), **content.get('devDependencies', {})}
                if 'react' in deps:
                    self._ui_framework_cache = 'react'
                    return 'react'
                elif 'vue' in deps:
                    self._ui_framework_cache = 'vue'
                    return 'vue'
                elif '@angular/core' in deps:
                    self._ui_framework_cache = 'angular'
                    return 'angular'
                elif 'electron' in deps:
                    self._ui_framework_cache = 'electron'
                    return 'electron'
            except Exception:
                pass

        self._ui_framework_cache = None
        return None

    async def _get_llm_framework_guidance(self, bug_description: str, file_contents: Dict[str, str]) -> str:
        """
        Ask the LLM to identify framework-specific constraints for testing.

        This is the intelligent approach - the LLM analyzes the actual code
        and bug context to provide relevant framework constraints, rather
        than relying on hardcoded heuristics.

        Returns framework-specific guidance string for the test generation prompt.
        """
        # Build a sample of the code for context
        code_sample = ""
        for path, content in list(file_contents.items())[:3]:
            truncated = content[:2000] if len(content) > 2000 else content
            code_sample += f"\n--- {path} ---\n{truncated}\n"

        prompt = f"""Analyze this code and identify any UI/framework-specific constraints that affect testing.

BUG/FEATURE: {bug_description}

CODE SAMPLE:
{code_sample}

TASK: Identify the UI framework (if any) and provide CRITICAL testing constraints.

Think about:
1. What UI framework is this? (Qt/PyQt, Tkinter, React, Vue, Angular, Electron, Flutter, SwiftUI, etc.)
2. What are the LIMITATIONS of this framework that could cause incorrect tests?
3. What assertions would be WRONG vs RIGHT for this framework?

OUTPUT FORMAT (plain text, will be inserted into test generation prompt):
If a UI framework is detected, provide constraints like:

FRAMEWORK CONSTRAINTS for [FrameworkName]:
==========================================
1. [Limitation 1 - what the framework does NOT support]
2. [Limitation 2]
...

CORRECT TESTING APPROACH:
- [How to properly test visual/UI elements in this framework]
- [What assertions to use vs avoid]

EXAMPLE:
- WRONG: [incorrect assertion approach]
- RIGHT: [correct assertion approach]

If no special framework constraints apply, respond with: NO_FRAMEWORK_CONSTRAINTS
"""

        try:
            response = await asyncio.to_thread(
                self.llm_client.generate,
                prompt=prompt,
                temperature=0.2,
                max_tokens=1500
            )

            if not response.success:
                logger.warning(f"LLM framework guidance failed: {response.error}")
                return self._get_framework_specific_guidance()  # Fall back to static

            content = response.content.strip()

            if "NO_FRAMEWORK_CONSTRAINTS" in content:
                return ""

            logger.info(f"LLM framework guidance received ({len(content)} chars)")
            return f"\n{content}\n"

        except Exception as e:
            logger.warning(f"LLM framework guidance error: {e}")
            return self._get_framework_specific_guidance()  # Fall back to static

    def _get_framework_specific_guidance(self) -> str:
        """
        Get framework-specific test generation guidance.

        GENERALIZED APPROACH: No hardcoded framework-specific rules.
        The LLM should analyze the code context to determine appropriate
        testing approaches. This ensures the solution works for:
        - Any framework (Qt, tkinter, React, etc.)
        - Any language
        - Any testing scenario
        """
        # GENERALIZED: Let the LLM figure out testing approach from code context
        # No hardcoded framework rules - they violate the generalization principle
        return ""

    async def get_framework_guidance_for_fix(self, bug_description: str, file_contents: Dict[str, str]) -> str:
        """
        Public async method for controllers to get framework guidance.

        GENERALIZED APPROACH: Let the LLM analyze the code context to determine
        the appropriate implementation approach. No hardcoded framework rules.

        Args:
            bug_description: The bug or feature being addressed
            file_contents: Dict of {filepath: content} for relevant files

        Returns:
            Empty string - guidance comes from test code alignment instead
        """
        # GENERALIZED: No hardcoded framework guidance
        # The fix prompt should include the TEST CODE so the LLM can
        # naturally align its implementation with what the test verifies.
        logger.info("Using generalized approach: fix will align with test code")
        return ""

    async def generate_bug_test(
        self,
        bug_description: str,
        error_trace: Optional[str],
        affected_files: List[str],
        root_cause: Optional[str] = None
    ) -> str:
        """
        Generate a test that reproduces the specific bug.

        Args:
            bug_description: User's description of the bug
            error_trace: Stack trace if available
            affected_files: List of files involved in the bug
            root_cause: Identified root cause (if known)

        Returns:
            Generated test code as a string, or empty string if manual testing required
        """
        # Check if language requires manual testing (e.g., GDScript, HTML)
        lang = self.language_detector.detect()
        if lang.test_framework == "manual":
            logger.info(f"[TestGen] {lang.name} requires manual testing - skipping automated test generation")
            logger.info(f"[TestGen] User must test by running the application")
            return ""  # Signal that manual testing is needed

        # Read affected files for context
        file_contents = {}
        for file_path in affected_files[:5]:  # Limit to 5 files
            try:
                full_path = self.project_dir / file_path
                if full_path.exists():
                    with open(full_path, 'r') as f:
                        file_contents[file_path] = f.read()
            except Exception as e:
                logger.warning(f"Could not read {file_path}: {e}")

        # GENERALIZED: No hardcoded framework guidance
        # LLM analyzes code context to determine appropriate testing approach
        logger.info("Using generalized approach: LLM will analyze code context for testing")
        framework_guidance = ""

        # Build prompt for LLM
        prompt = self._build_test_generation_prompt(
            bug_description=bug_description,
            error_trace=error_trace,
            file_contents=file_contents,
            root_cause=root_cause,
            framework_guidance=framework_guidance
        )

        # Generate test via LLM
        try:
            response = await asyncio.to_thread(
                self.llm_client.generate,
                prompt=prompt,
                model=None,
                temperature=0.3,  # Lower temp for more deterministic code
                max_tokens=4000
            )

            if not response.success:
                raise Exception(f"LLM generation failed: {response.error}")

            test_code = response.content

            # Extract code from markdown if present
            test_code = self._extract_code(test_code)

            logger.info("Generated bug-specific test")
            return test_code

        except Exception as e:
            logger.error(f"Failed to generate bug test: {e}")
            # Return a minimal test template
            return self._generate_fallback_test(bug_description, error_trace)

    async def generate_unit_test(
        self,
        unit_description: str,
        affected_files: List[str],
        test_approach: str = "",
        test_assertions: List[str] = None,
        error_details: str = ""
    ) -> str:
        """
        Generate a targeted test for a specific debug unit.

        This is different from generate_bug_test() in that it:
        1. Focuses on ONE specific aspect of the bug
        2. Uses the provided test approach and assertions
        3. Is more surgical and targeted

        Args:
            unit_description: Description of what this unit tests
            affected_files: Files involved in this unit
            test_approach: Suggested approach for testing
            test_assertions: Specific assertions to include
            error_details: Specific error for this unit

        Returns:
            Generated test code as a string, or empty string if manual testing required
        """
        # Check if language requires manual testing (e.g., GDScript, HTML)
        lang = self.language_detector.detect()
        if lang.test_framework == "manual":
            logger.info(f"[TestGen] {lang.name} requires manual testing - skipping automated test generation")
            return ""  # Signal that manual testing is needed

        test_assertions = test_assertions or []

        # Read affected files
        file_contents = {}
        for file_path in affected_files[:3]:
            try:
                full_path = self.project_dir / file_path
                if full_path.exists():
                    file_contents[file_path] = full_path.read_text(encoding='utf-8', errors='replace')
            except Exception as e:
                logger.warning(f"Could not read {file_path}: {e}")

        # Detect if this is a GUI project
        ui_framework = self._detect_ui_framework()
        is_gui = ui_framework is not None

        # Build prompt
        prompt = self._build_unit_test_prompt(
            unit_description=unit_description,
            file_contents=file_contents,
            test_approach=test_approach,
            test_assertions=test_assertions,
            error_details=error_details,
            is_gui=is_gui,
            ui_framework=ui_framework
        )

        try:
            response = await asyncio.to_thread(
                self.llm_client.generate,
                prompt=prompt,
                temperature=0.3,
                max_tokens=3000
            )

            if not response.success:
                raise Exception(f"LLM generation failed: {response.error}")

            test_code = self._extract_code(response.content)
            logger.info(f"Generated unit test for: {unit_description[:50]}")
            return test_code

        except Exception as e:
            logger.error(f"Failed to generate unit test: {e}")
            return self._generate_fallback_unit_test(unit_description)

    def _build_unit_test_prompt(
        self,
        unit_description: str,
        file_contents: Dict[str, str],
        test_approach: str,
        test_assertions: List[str],
        error_details: str,
        is_gui: bool,
        ui_framework: Optional[str]
    ) -> str:
        """Build prompt for unit test generation."""

        lang = self.language_detector.detect()

        files_context = ""
        for path, content in file_contents.items():
            if len(content) > 2000:
                content = content[:2000] + "\n... (truncated)"
            files_context += f"\n--- {path} ---\n{content}\n"

        # GUI-specific functional testing guidance
        gui_guidance = ""
        if is_gui:
            gui_guidance = f"""
GUI FUNCTIONAL TESTING GUIDANCE ({ui_framework}):
================================================
This is a GUI application, but you should test FUNCTIONAL aspects, not visual ones.

WHAT TO TEST (Functional - Automatable):
- Function/method return values
- State changes after operations
- Event handler logic (does clicking trigger correct action?)
- Data validation and transformation
- API calls and responses
- Error handling paths
- Configuration/settings application

WHAT NOT TO TEST (Visual - Human verification):
- Colors, fonts, sizes
- Layout and positioning
- Animation smoothness
- "Does it look right?"

APPROACH:
1. Import the module/class being tested
2. Call methods directly or simulate events
3. Assert on STATE changes, not appearance
4. Use mocks for external dependencies

EXAMPLE for {ui_framework}:
```python
def test_button_click_updates_state():
    # Test the LOGIC, not the appearance
    widget = MyWidget()
    widget.on_button_clicked()  # Simulate the action
    assert widget.data_updated == True  # Check state changed
    assert widget.error_message is None  # Check no errors
```
"""

        assertions_text = "\n".join(f"- {a}" for a in test_assertions) if test_assertions else "Not specified"

        return f"""Generate a TARGETED pytest test for this specific unit.

UNIT DESCRIPTION:
{unit_description}

ERROR DETAILS:
{error_details or 'Not specified'}

SUGGESTED TEST APPROACH:
{test_approach or 'Test the described functionality'}

EXPECTED ASSERTIONS:
{assertions_text}

CODE CONTEXT:
{files_context}
{gui_guidance}

REQUIREMENTS:
1. Test ONLY this specific unit - keep it focused
2. The test should FAIL when the bug exists
3. The test should PASS after the bug is fixed
4. Use proper {lang.test_framework} assertions
5. Include clear docstrings explaining what the test verifies
6. Avoid testing visual/aesthetic aspects for GUI apps
7. Test LOGIC, STATE, and BEHAVIOR - not appearance

Generate ONLY the {lang.name} test code, no explanations.
"""

    def _generate_fallback_unit_test(self, unit_description: str) -> str:
        """Generate fallback test when LLM fails."""
        import re
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', unit_description[:30])

        return f'''"""
Unit test (fallback template).
Unit: {unit_description[:100]}
"""

import pytest


class TestUnit_{safe_name}:
    """Test case for: {unit_description[:50]}"""

    @pytest.mark.skip(reason="Fallback test - needs manual implementation")
    def test_unit_functionality(self):
        """
        TODO: Implement test for this unit.

        Unit: {unit_description}
        """
        assert False, "Test not implemented"
'''

    async def generate_functional_gui_tests(
        self,
        bug_description: str,
        affected_files: List[str],
        ui_framework: str
    ) -> List[Dict[str, str]]:
        """
        Generate FUNCTIONAL tests for GUI applications.

        Instead of testing visual appearance, these tests verify:
        - State changes
        - Event handler logic
        - Data flow
        - API interactions
        - Error handling

        Args:
            bug_description: The bug being fixed
            affected_files: Files involved
            ui_framework: Detected UI framework

        Returns:
            List of dicts with 'name' and 'code' for each test
        """
        file_contents = {}
        for file_path in affected_files[:5]:
            try:
                full_path = self.project_dir / file_path
                if full_path.exists():
                    file_contents[file_path] = full_path.read_text(encoding='utf-8', errors='replace')
            except Exception as e:
                logger.warning(f"Could not read {file_path}: {e}")

        prompt = f"""Analyze this GUI bug and generate FUNCTIONAL tests (not visual tests).

BUG DESCRIPTION:
{bug_description}

UI FRAMEWORK: {ui_framework}

AFFECTED FILES:
{chr(10).join(f"--- {p} ---{chr(10)}{c[:1500]}" for p, c in file_contents.items())}

TASK: Identify FUNCTIONAL aspects that can be tested automatically.

For each testable aspect, provide:
1. Test name
2. What it tests (logic, state, data flow - NOT appearance)
3. The test code

OUTPUT FORMAT (JSON):
{{
    "tests": [
        {{
            "name": "test_function_name",
            "description": "Tests that X logic works correctly",
            "code": "def test_function_name():\\n    # test code here"
        }}
    ]
}}

RULES:
1. Test LOGIC and STATE, not visual appearance
2. Mock external dependencies where needed
3. Each test should be independent
4. Focus on the bug's FUNCTIONAL impact
"""

        try:
            response = await asyncio.to_thread(
                self.llm_client.generate,
                prompt=prompt,
                temperature=0.3,
                max_tokens=4000
            )

            if not response.success:
                return []

            import json
            import re

            content = response.content.strip()
            json_match = re.search(r'\{[\s\S]*\}', content)
            if not json_match:
                return []

            data = json.loads(json_match.group())
            tests = []
            for t in data.get('tests', []):
                tests.append({
                    'name': t.get('name', 'test_unknown'),
                    'code': t.get('code', ''),
                    'description': t.get('description', '')
                })

            logger.info(f"Generated {len(tests)} functional GUI tests")
            return tests

        except Exception as e:
            logger.error(f"Failed to generate functional GUI tests: {e}")
            return []

    def _build_test_generation_prompt(
        self,
        bug_description: str,
        error_trace: Optional[str],
        file_contents: Dict[str, str],
        root_cause: Optional[str],
        framework_guidance: Optional[str] = None
    ) -> str:
        """Build the prompt for test generation (language-aware and framework-aware)."""
        # Get detected language
        lang = self.language_detector.detect()
        lang_context = self.language_detector.get_language_context_for_llm()

        # Use provided framework guidance (from LLM) or fall back to static detection
        if framework_guidance is None:
            framework_guidance = self._get_framework_specific_guidance()

        files_context = ""
        for path, content in file_contents.items():
            # Truncate large files
            if len(content) > 3000:
                content = content[:3000] + "\n... (truncated)"
            files_context += f"\n--- {path} ---\n{content}\n"

        # Language-specific example
        example = self._get_test_example(lang)

        return f"""Generate a {lang.test_framework} test that REPRODUCES this bug.

{lang_context}

BUG DESCRIPTION:
{bug_description}

{"ERROR TRACE:" + chr(10) + error_trace if error_trace else ""}

{"ROOT CAUSE (if identified):" + chr(10) + root_cause if root_cause else ""}

AFFECTED FILES:
{files_context}

REQUIREMENTS:
1. The test should FAIL when the bug exists
2. The test should PASS after the bug is fixed
3. Import all necessary modules
4. Use proper {lang.test_framework} assertions
5. Include clear docstrings/comments explaining what the test verifies
6. Keep the test focused and minimal
7. Follow {lang.name} best practices

ROBUSTNESS RULES:
- Avoid brittle assertions (e.g., exact pixel matching, rigid string equality for dynamic values).
- Use fuzzy matching where appropriate.
- Ensure setup/teardown is clean to prevent side effects.
- The test MUST be accurate: a "PASS" should genuinely mean the bug is fixed.
- The test MUST NOT be a false negative.

VISUAL TESTING PRINCIPLE:
- Visual verification (colors, fonts, appearance, look-and-feel) is BEST LEFT TO THE END USER
- Do NOT try to test visual aesthetics - test that CODE CHANGES were made correctly
- For UI bugs: test that the fix code exists and is called, not that it "looks right"
- Focus on testing logic, configuration, and behavior - not subjective visual outcomes
{framework_guidance}
Generate ONLY the {lang.name} test code, no explanations.
{example}
"""

    def _get_test_example(self, lang: LanguageInfo) -> str:
        """Get a language-specific test example."""
        examples = {
            "python": '''Example structure:
```python
import pytest
# ... other imports

class TestBug_DescriptiveName:
    def test_bug_reproduction(self):
        # Setup conditions
        # Execute code that triggers bug
        # Assert expected behavior
        assert result == expected, "Descriptive error message"
```''',
            "javascript": '''Example structure:
```javascript
const { describe, it, expect } = require('@jest/globals');
// ... other imports

describe('Bug: DescriptiveName', () => {
    it('should reproduce the bug condition', () => {
        // Setup conditions
        // Execute code that triggers bug
        // Assert expected behavior
        expect(result).toBe(expected);
    });
});
```''',
            "typescript": '''Example structure:
```typescript
import { describe, it, expect } from '@jest/globals';
// ... other imports

describe('Bug: DescriptiveName', () => {
    it('should reproduce the bug condition', () => {
        // Setup conditions
        // Execute code that triggers bug
        // Assert expected behavior
        expect(result).toBe(expected);
    });
});
```''',
            "go": '''Example structure:
```go
package main

import "testing"

func TestBug_DescriptiveName(t *testing.T) {
    // Setup conditions
    // Execute code that triggers bug
    // Assert expected behavior
    if result != expected {
        t.Errorf("Expected %v, got %v", expected, result)
    }
}
```''',
            "rust": '''Example structure:
```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bug_descriptive_name() {
        // Setup conditions
        // Execute code that triggers bug
        // Assert expected behavior
        assert_eq!(result, expected, "Descriptive error message");
    }
}
```''',
            "java": '''Example structure:
```java
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestBug_DescriptiveName {
    @Test
    void testBugReproduction() {
        // Setup conditions
        // Execute code that triggers bug
        // Assert expected behavior
        assertEquals(expected, result, "Descriptive error message");
    }
}
```''',
        }
        return examples.get(lang.short_name, examples["python"])

    def _extract_code(self, response: str, expected_type: str = "py") -> str:
        """
        Extract code from LLM response using iron-clad extraction.

        Uses the centralized extraction from llm_client which handles:
        - Thinking/reasoning tags from various models
        - Multiple code blocks (picks the best/largest)
        - Quality scoring (completeness, bracket balance)
        - Unfenced code detection
        """
        from ..llm_client import extract_best_code_block, strip_thinking_content

        # First strip any thinking content
        response = strip_thinking_content(response)

        # Use iron-clad extraction with quality scoring
        return extract_best_code_block(response, expected_type)

    def _generate_fallback_test(self, bug_description: str, error_trace: Optional[str]) -> str:
        """Generate a minimal test when LLM fails."""
        from datetime import datetime
        import re

        # Create safe test name
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', bug_description[:30])

        return f'''"""
Bug-specific test (fallback template).
Bug: {bug_description[:100]}
"""

import pytest


class TestBug_{safe_name}:
    """Test case for: {bug_description[:50]}"""

    @pytest.mark.skip(reason="Fallback test - needs manual implementation")
    def test_bug_reproduction(self):
        """
        TODO: Implement test that reproduces the bug.

        Bug description: {bug_description}

        Error trace:
        {error_trace if error_trace else "Not provided"}
        """
        # This test needs manual implementation
        assert False, "Test not implemented"
'''

    def _get_model(self) -> str:
        """Get the LLM model to use."""
        from agents.common.config_loader import AgentConfigLoader
        try:
            config = AgentConfigLoader.load_config('coding_agent')
            return config.get_llm_model()
        except Exception:
            return "RAICA-Model1"  # Fallback

    def _get_test_command(self, test_file: Path) -> List[str]:
        """Get the language-appropriate test command for a file."""
        lang = self.language_detector.detect()

        # Use language-specific test command, but replace generic args with specific file
        base_cmd = lang.test_command.copy()

        # Most test frameworks accept the file path as an argument
        if lang.short_name == "python":
            python_path = self._get_project_python_path()
            return [python_path, "-m", "pytest", str(test_file), "-v", "--tb=short", "-x"]
        elif lang.short_name in ["javascript", "typescript"]:
            return ["npx", "jest", str(test_file), "--verbose"]
        elif lang.short_name == "go":
            return ["go", "test", "-v", "-run", test_file.stem, "./..."]
        elif lang.short_name == "rust":
            return ["cargo", "test", test_file.stem, "--", "--nocapture"]
        elif lang.short_name == "java":
            # Maven/Gradle - test specific class
            return ["mvn", "test", f"-Dtest={test_file.stem}"]
        else:
            # Fall back to base command with file appended
            return base_cmd + [str(test_file)]

    async def run_test(self, test_file: Path, timeout: int = 60) -> TestResult:
        """
        Run a test file and return the result (language-aware).

        Args:
            test_file: Path to the test file
            timeout: Maximum seconds to wait

        Returns:
            TestResult with pass/fail status and output
        """
        # Check if language requires manual testing
        lang = self.language_detector.detect()
        if lang.test_framework == "manual":
            logger.info(f"[TestRun] {lang.name} requires manual testing - cannot run automated tests")
            return TestResult(
                passed=True,  # Assume pass - user must verify manually
                output=f"MANUAL TESTING REQUIRED: {lang.name} projects must be tested by running the application.\n"
                       f"Please run: {' '.join(lang.test_command)}",
                error=None,
                duration_seconds=0.0
            )

        import time
        start_time = time.time()

        try:
            # Get language-appropriate test command
            cmd = self._get_test_command(test_file)
            logger.info(f"Running test with command: {' '.join(cmd)}")

            result = await asyncio.to_thread(
                subprocess.run,
                cmd,
                cwd=str(self.project_dir),
                capture_output=True,
                text=True,
                timeout=timeout
            )

            duration = time.time() - start_time
            passed = result.returncode == 0

            return TestResult(
                passed=passed,
                output=result.stdout,
                error=(result.stdout + "\n" + result.stderr) if not passed else None,
                duration_seconds=duration
            )

        except subprocess.TimeoutExpired:
            return TestResult(
                passed=False,
                output="",
                error=f"Test timed out after {timeout} seconds",
                duration_seconds=timeout
            )
        except Exception as e:
            return TestResult(
                passed=False,
                output="",
                error=str(e),
                duration_seconds=time.time() - start_time
            )

    async def verify_test_fails(self, test_file: Path) -> bool:
        """
        Verify the bug test FAILS (confirming bug exists).

        Returns True if test fails (expected before fix).
        """
        result = await self.run_test(test_file)
        if not result.passed:
            logger.info("Bug test FAILS as expected (bug confirmed)")
            return True
        else:
            logger.warning("Bug test PASSES - hypothesis may be wrong")
            return False

    async def verify_test_passes(self, test_file: Path, timeout: int = 60) -> bool:
        """
        Verify the bug test PASSES (confirming bug is fixed).

        Args:
            test_file: Path to test file
            timeout: Maximum seconds to wait (default 60)

        Returns True if test passes (expected after fix).
        """
        result = await self.run_test(test_file, timeout=timeout)
        if result.passed:
            logger.info("Bug test PASSES - fix verified!")
            return True
        else:
            logger.warning(f"Bug test still FAILS - fix incomplete: {result.error}")
            return False

    async def get_test_error(self, test_file: Path) -> Optional[str]:
        """
        Get the error message from running a test.

        Returns the error message if test fails, None if passes.
        """
        result = await self.run_test(test_file)
        return result.error

    def identify_relevant_tests(self, modified_files: List[str]) -> List[Path]:
        """
        Identify existing tests that verify the modified files.
        Uses naming conventions and import scanning.
        """
        relevant_tests = set()
        
        # Gather all test files
        all_tests = []
        test_roots = [
            self.project_dir / "tests",
            self.project_dir / "test",
            self.project_dir
        ]
        
        for root in test_roots:
            if root.exists():
                if root.is_dir():
                    all_tests.extend(list(root.rglob("test_*.py")))
                    all_tests.extend(list(root.rglob("*_test.py")))
                else:
                    # project dir itself
                    all_tests.extend(list(root.glob("test_*.py")))

        all_tests = list(set(all_tests)) # unique
        
        # Use Dependency Graph for robust detection
        from ..services.dependency_graph import DependencyGraphService
        graph = DependencyGraphService(self.project_dir)
        graph.build_graph()
        
        for mod_file in modified_files:
            # Get all files that depend on this modified file
            dependents = graph.get_dependents(mod_file, recursive=True)
            
            # Also check the file itself if it's a test
            if "test" in mod_file or "tests" in mod_file:
                 dependents.add(mod_file)

            # Filter for test files
            for dep in dependents:
                if "test" in dep or "tests" in dep: # Simple heuristics for test files
                     # Confirm it's a python file and exists
                     p = self.project_dir / dep
                     if p.exists() and p.name.endswith('.py') and (p.name.startswith("test_") or p.name.endswith("_test.py")):
                         # EXCLUDE historical bug reproduction tests
                         if not p.name.startswith("test_bug_"):
                             relevant_tests.add(p)
            
            # Fallback: maintain direct name matching for safety
            mod_path = Path(mod_file)
            mod_stem = mod_path.stem
            for test in all_tests:
                if test.name.startswith("test_bug_"):
                    continue # Skip bug tests
                
                if f"test_{mod_stem}" in test.name or f"{mod_stem}_test" in test.name:
                    relevant_tests.add(test)
        
        # Filter out test files with broken imports
        # This prevents false positive regressions from test pollution
        validated_tests = []
        for test_path in relevant_tests:
            if self._test_file_is_valid(test_path):
                validated_tests.append(test_path)
            else:
                logger.warning(f"Skipping test with broken imports: {test_path}")
        
        return validated_tests
    
    def _test_file_is_valid(self, test_path: Path) -> bool:
        """
        Quick check if a test file can be collected without import errors.
        Returns False if the file has broken imports.
        """
        try:
            result = subprocess.run(
                [self._get_project_python_path(), "-c", f"import ast; ast.parse(open('{test_path}').read())"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=str(self.project_dir)
            )
            if result.returncode != 0:
                return False
            
            # Check for obvious import issues by reading the file
            content = test_path.read_text(encoding='utf-8', errors='replace')
            
            # Look for imports that are known to be problematic
            problematic_imports = ['astroid', 'pylint']  # These are dev tools, not runtime deps
            for line in content.split('\n'):
                line = line.strip()
                if line.startswith('import ') or line.startswith('from '):
                    for prob_import in problematic_imports:
                        if prob_import in line:
                            return False
            
            return True
        except Exception:
            return False

    async def run_targeted_tests(self, test_paths: List[Path], timeout: int = 60) -> TestResult:
        """
        Run a specific list of test files.
        
        Args:
            test_paths: List of test files to run
            timeout: Timeout in seconds
            
        Returns:
            TestResult
        """
        if not test_paths:
            return TestResult(True, "No relevant tests identified to run.", duration_seconds=0.0)
            
        import time
        start_time = time.time()
        
        try:
            python_path = self._get_project_python_path()
            cmd = [python_path, "-m", "pytest", "-v", "--tb=short"]
            cmd.extend([str(p) for p in test_paths])
            
            result = await asyncio.to_thread(
                subprocess.run,
                cmd,
                cwd=str(self.project_dir),
                capture_output=True,
                text=True,
                timeout=timeout
            )

            duration = time.time() - start_time
            passed = result.returncode == 0

            return TestResult(
                passed=passed,
                output=result.stdout,
                error=(result.stdout + "\n" + result.stderr) if not passed else None,
                duration_seconds=duration
            )
            
        except subprocess.TimeoutExpired:
             return TestResult(False, "", f"Targeted tests timed out after {timeout}s", timeout)
        except Exception as e:
             return TestResult(False, "", str(e), time.time() - start_time)

    async def run_all_project_tests(self, timeout: int = 120) -> TestResult:
        """
        Run all tests in the project to check for regressions.

        Returns:
            TestResult for the entire test suite
        """
        import time
        start_time = time.time()

        # Check for test directory or test files
        test_locations = [
            self.project_dir / "tests",
            self.project_dir / "test",
        ]

        test_dir = None
        for loc in test_locations:
            if loc.exists():
                test_dir = loc
                break

        # Also look for test_*.py files in project root
        test_files = list(self.project_dir.glob("test_*.py"))

        if not test_dir and not test_files:
            logger.info("No existing tests found in project")
            return TestResult(
                passed=True,
                output="No existing tests found",
                duration_seconds=0.0
            )

        try:
            # Run pytest on the whole project
            python_path = self._get_project_python_path()
            cmd = [python_path, "-m", "pytest", "-v", "--tb=short"]
            if test_dir:
                cmd.append(str(test_dir))
            else:
                cmd.extend([str(f) for f in test_files])

            result = await asyncio.to_thread(
                subprocess.run,
                cmd,
                cwd=str(self.project_dir),
                capture_output=True,
                text=True,
                timeout=timeout
            )

            duration = time.time() - start_time
            passed = result.returncode == 0

            return TestResult(
                passed=passed,
                output=result.stdout,
                error=(result.stdout + "\n" + result.stderr) if not passed else None,
                duration_seconds=duration
            )

        except subprocess.TimeoutExpired:
            return TestResult(
                passed=False,
                output="",
                error=f"Tests timed out after {timeout} seconds",
                duration_seconds=timeout
            )
        except Exception as e:
            return TestResult(
                passed=False,
                output="",
                error=str(e),
                duration_seconds=time.time() - start_time
            )
